run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - typecheck
    - exportloopref
    - prealloc
    # - wls # excluded from linters list because produces too many noise
    - staticcheck
    - unused
    - contextcheck
    - durationcheck
    - errname
    - exhaustive
    - gocritic
    - gofmt
    - nilerr
    - nilnil
    - usestdlibvars
