# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: KaymeKaydex/go-vshard-router

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2

      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
        with:
          # The first run is for GitHub Actions error format.
          args: --config=.golangci.yaml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # The second run is for human-readable error format with a file name
          # and a line number.
          args: --out-${NO_FUTURE}format colored-line-number --config=.golangci.yaml